<?php

namespace AppBundle\WSServer\Command;
use AppBundle\Game\GamesRepository;
use AppBundle\Game\GameBuilderSupervisor;
use AppBundle\Game\GameBuilder\PrivateGameBuilder;
use AppBundle\WSServer\Message;
use AppBundle\Tests\WSServer\ConnectionMock;
use AppBundle\ConfigContainer;
use AppBundle\Game\PlayerBuilderSupervisor;
use AppBundle\Game\PlayerBuilder\HumanPlayerBuilder;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-15 at 07:51:55.
 */
class CloseGameTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CreatePrivateGame
     */
    protected $object;

    /**
     * @var Player
     */
    private $closingPlayer;

    /**
     * @var Player
     */
    private $secondPlayer;
    
    /**
     *
     * @var GamesRepository
     */
    private $gamesRepository;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $config = new ConfigContainer(array(
            'boardWidth' => 20,
            'boardHeight' => 20
        ));
        $gameBuilder = new GameBuilderSupervisor($config);
        $this->gamesRepository = new GamesRepository();
        $playerBuilder = new PlayerBuilderSupervisor();
        
        $playerBuilder->setPlayerName('closingPlayer');
        $this->closingPlayer = $playerBuilder->createPlayer(new HumanPlayerBuilder());
        
        $playerBuilder->setPlayerName('secondPlayer');
        $this->secondPlayer = $playerBuilder->createPlayer(new HumanPlayerBuilder());
        
        $this->closingPlayer->setConnection(new ConnectionMock());
        $this->secondPlayer->setConnection(new ConnectionMock());
        $gameBuilder->setCreator($this->closingPlayer);
        $game = $gameBuilder->createGame(new PrivateGameBuilder());
        $game->addPlayer($this->secondPlayer);
        $this->gamesRepository->attach($game);
        
        $this->object = new CloseGame($this->gamesRepository);
    }

    /**
     * @covers AppBundle\WSServer\Command\CreatePrivateGame::run
     */
    public function testSendedToSecondPlayerExitMessageAfterRun() {
        $message = new Message();
        //there is no content of message
        $message->setConnection($this->closingPlayer->getConnection());
        
        $this->object->run($message);
        $messageToSecondPlayer = json_decode($this->secondPlayer->getConnection()->getSendedData(), true);
        $expectedMessage = array(
            'command' => 'CloseGame',
            'parameters' => array()
        );
        $this->assertEquals($expectedMessage, $messageToSecondPlayer);
    }
    /**
     * @covers AppBundle\WSServer\Command\CreatePrivateGame::run
     */
    public function testGameIsDestroyedAfterRun() {
        $message = new Message();
        //there is no content of message
        $message->setConnection($this->closingPlayer->getConnection());
        
        $this->object->run($message);
        $this->gamesRepository->count();
        $this->assertEquals(0, $this->gamesRepository->count(), 'GameRepository isnt empty after close game');
    }

    /**
     * @covers AppBundle\WSServer\Command\CreatePrivateGame::getCommandName
     */
    public function testGetCommandName() {
        $this->assertEquals('CloseGame', $this->object->getCommandName());
    }

    /**
     * @covers AppBundle\WSServer\Command\CreatePrivateGame::getType
     */
    public function testGetType() {
        $this->assertEquals(WSCommandInterface::ON_CLOSE_TYPE, $this->object->getType());
    }

}
