<?php

namespace AppBundle\WSServer\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-11 at 10:29:50.
 */
class MakeMoveTest extends \PHPUnit_Framework_TestCase {

    const BOARD_WIDTH = 20;
    const BOARD_HEIGHT = 10;

    /**
     * @var MakeMove
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $gameSystem = new \AppBundle\Game\GameSystem(array('boardWidth'=>20,'boardHeight'=>10));
        $this->object = new MakeMove($gameSystem);
    }

    /**
     * @covers AppBundle\WSServer\Command\MakeMove::run
     * @todo   Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppBundle\WSServer\Command\MakeMove::validateParameters
     * @expectedException Exception
     */
    public function testValidateParametersWhenXNonExists() {
        $parameters = array('y'=>10);
        $this->object->validateParameters($parameters);
    }
    /**
     * @covers AppBundle\WSServer\Command\MakeMove::validateParameters
     * @expectedException Exception
     */
    public function testValidateParametersWhenYNonExists() {
        $parameters = array('x'=>10);
        $this->object->validateParameters($parameters);
    }

}
