<?php

namespace AppBundle\Storage\Tree;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-03 at 10:49:20.
 */
class TreeNodeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TreeNode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TreeNode;
    }


    /**
     * @covers AppBundle\Storage\Tree\TreeNode::getLeaves
     */
    public function testGetLeaves() {
        $node = new TreeNode();
        $node2 = new TreeNode();
        $node3 = new TreeNode();
        $this->object->addChild($node);
        $this->object->addChild($node2);
        $this->object->addChild($node3);
        $leaf = new TreeNode();
        $leaf1 = new TreeNode();
        $leaf2 = new TreeNode();
        $node->addChild($leaf);
        $node->addChild($leaf1);
        $node2->addChild($leaf2);
        
        //node 3 dont have child, so it is leaf too
        $this->assertEquals(4, count($this->object->getLeaves()));
    }

}
